# Étape 1 : Utilise une image Node.js LTS
FROM node:18

# Crée un dossier pour l'app dans le conteneur
WORKDIR /app

# Copie les fichiers nécessaires
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# Démarre l'application (modifie selon ton point d'entrée)
CMD ["npm", "start"]